# Generated by Django 2.1.1 on 2018-09-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_table', '0002_auto_20180917_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='type',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter an instrument genre e.g. Equity, Futures, ETF, Fund Index Option', max_length=50),
        ),
    ]
