# Generated by Django 2.1.1 on 2018-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_table', '0003_auto_20180918_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.TextField(help_text='Enter the name of an instrument', max_length=50),
        ),
    ]
