# Generated by Django 2.1.1 on 2018-09-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an instrument genre e.g. Equity, Futures, ETF, Fund Index Option', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('name', models.TextField(help_text='Enter the name of an instrument', max_length=50)),
                ('exchange', models.CharField(help_text='The name of exchange institution', max_length=13, verbose_name='Exchange')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this instrument', to='Show_Table.Genre')),
            ],
        ),
    ]
