# Generated by Django 2.1.1 on 2018-09-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show_Table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
            ],
        ),
    ]
