# Generated by Django 2.1.1 on 2018-09-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a instrument genre (e.g. Equity)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('name', models.TextField(help_text='Enter a of the instrument', max_length=50)),
                ('exchange', models.CharField(help_text='The name of exchange institution', max_length=13, verbose_name='Exchange')),
                ('type', models.CharField(help_text='S for stock; E for Equity ...etc', max_length=1, verbose_name='Type')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this instrument', to='view_table.Genre')),
            ],
        ),
        migrations.RemoveField(
            model_name='alibaba_group_holding_limited',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Alibaba_Group_Holding_Limited',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
